ブックマーク機能を実装
illionillion/tech-museum pull request #152
Opened 2024-11-02 04:11 UTC by yuto-trd

Closes #147

## 概要

## 変更点

## 追加情報

2024-11-02 11:19 UTC, illionillion requested changes
@yuto-trd 
関数の共通化だけお願いします。

2024-11-02 11:19 UTC, illionillion commented on components/disclosure/profile-tabs.tsx
> +
`top-page-tabs.tsx`と同じロジックなので共通化してください

それと型定義や定数をこう書き換えるのはどうですか？
```suggestion
function joinArticles(fetchedArticles: Awaited<ReturnType<typeof fetchArticlesByUsername>> | Awaited<ReturnType<typeof fetchBookmarksByUsername>>, articles: Awaited<ReturnType<typeof getArticleList>>) {
  return articles.map((article) => {
    const isHit = fetchedArticles.some(
      (item) => item.articleURL === article.slug,
    )
    return isHit ? article : null // 一致した場合は記事を返し、一致しない場合はnull
  })
    // nullを除外して最終的なlikedArticlesを得る
    .filter((article) => article !== null)
}
```

2024-11-02 12:09 UTC, yuto-trd commented on components/disclosure/profile-tabs.tsx
> +
良いと思います！それで行きましょう

2024-11-02 12:23 UTC, yuto-trd commented
@illionillion 変更しました

2024-11-02 12:56 UTC, illionillion commented
> @illionillion 変更しました

@yuto-trd ビルドが失敗しているようなので修正お願いします。

2024-11-02 13:05 UTC, yuto-trd commented
@illionillion ビルド通ったよー

2024-11-03 02:00 UTC, illionillion approved these changes
LGTM

2024-11-03 02:01 UTC, merged